### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por id
GET http://localhost:1234/movies/b9b7ed53-ede1-11ee-a665-18c04dd8e4c7

### Recuperar todas las peliculas por un genero
GET http://localhost:1234/movies?genre=Drama

### Crear una pelicula con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "sql": "SELECT * FROM users",
    "title": "King Kong",
    "year": 1988,
    "director": "No se quien polainas",
    "duration": 188,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ]
}

### Borrar una pelicula
DELETE http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf


### Actualizar una pelicula
PATCH http://localhost:1234/movies/deccfafa33-cadekakhkhfd
Content-Type: application/json

{
    "year": 1993
}